<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <PackageId>AvenNovel.SharedCode</PackageId>
	  <Version>1.0.1</Version>
	  <Authors>Aven</Authors>
	  <Description>Shared code blocks for Aven novel</Description>
	  <PackageTags>sharedcode;novel</PackageTags>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <RepositoryUrl>https://github.com/ban/repo</RepositoryUrl>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.13" />
  </ItemGroup>

</Project>
