name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT: SharedCode/SharedCode.csproj # <-- đổi cho đúng

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore ${{ env.PROJECT }}
      - run: dotnet build ${{ env.PROJECT }} -c Release --no-restore
      - run: dotnet pack ${{ env.PROJECT }} -c Release --no-build -o ./nupkgs

      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to nuget.org
        run: >
          dotnet nuget push ./nupkgs/*.nupkg
          --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate
